---
driver:
  # name: vagrant
  # vm_hostname: bit-lab-ws01-mg
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  #pre_salt_command: 'Remove-Item –path C:\Users\vagrant\AppData\Local\Temp\kitchen\var\cache\salt\minion\files\base –recurse'
  install_strategy: always
  formula: bit_win_hardening
  pillars_from_files:
    bit_win_hardening.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
        - bit_win_hardening

platforms:
  # - name: win2012r2-a
  #   driver:
  #     box: mwrock/Windows2012R2
  - name: debian
    driver_config:
      image: debian

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
          - bit_win_hardening

verifier:
  name: shell
  remote_exec: false
  command: .venv/bin/py.test -s --connection=docker  --hosts=root@$KITCHEN_CONTAINER_ID --html=reports/$KITCHEN_INSTANCE.html --self-contained-html --junit-xml=reports/junit-$KITCHEN_INSTANCE.xml tests/integration/$KITCHEN_SUITE
